### PR TITLE
Add Ruby 2.3 to Travis matrix

### PR DESCRIPTION
**Pull request by mikeastock**

### CODE REVIEW

**Comment by mikeastock** [comment]
Looks like rvm doesn't have a binary for Ruby 2.3. Do you prefer to only use binaries?

**Comment by jnunemaker** [comment]
I noticed this on a different project (that 2.3 isn't there). I don't really care how it works. If you know of another way to make 2.3 work, I'm open to that.

**Comment by mikeastock** [comment]
So it seems that if you specify the patch version `rvm` can find and install Ruby 2.3.0.

**Comment by jnunemaker** [comment]
> So it seems that if you specify the patch version rvm can find and install Ruby 2.3.0.

Seems fine to me. I guess only downside is it won't upgrade with patch upgrades.

**Comment by mikeastock** [comment]
This PR should be good to go then.

**Comment by jnunemaker** [comment]
Thanks!

**Pull request merged**
