### PR TITLE
add frozen_string_literal pragma to all files

### PR DESCRIPTION
**Pull request by ritikesh**

### CODE REVIEW

**Comment by ritikesh** [comment]
@jnunemaker ping.

**Comment by jnunemaker** [comment]
@ritikesh Hi there! Thanks for the ping as this had slipped past me. Did you check each of the files to see if there were any modification of strings that would cause problems with this or just add the magic comment? I know the tests are passing, but I won't claim 100% test coverage. I just don't want to break anything for anyone.

**Comment by ritikesh** [comment]
Hi @jnunemaker, guilty of over-depending on the tests. I'll have a look and give you a confirmation on the same. Thanks!

**Comment by ritikesh** [comment]
Hey @jnunemaker, I looked at the code. Things look okay to me. I did modify some code however: 
1. removing redundant `.freeze` on constants
2. reducing redundant allocations
3. changed string literals

**Pull request merged**
