### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by henrik**
This library is 7 1/2 years old – might it be time to consider it mature? :)

This is not intended as a dig but as a practical concern: I noticed the pre-1.0 version when updating gems and reflected on the fact that if it was post 1.0 and used semantic versioning, I could have more easily judged the impact of the upgrade.

I know the contribution guidelines say don't mess with the version, but it's hard to avoid in this case :D

### CODE REVIEW

**Comment by jnunemaker** [comment]
Fair. I've thought about it for a while, but it feels so permanent and big. The hilarious thing is I'm not sure I even have a 1.0 gem. Haha. I'll think about this for a bit and see if there is anything big that should be changed prior.

**Comment by jnunemaker** [comment]
By bit I mean I've added a task to revisit in a week.

**Comment by henrik** [comment]
:) :thumbsup:

**Comment by jnunemaker** [comment]
Haven't had time to review this yet, but still on my list.

**Comment by jnunemaker** [comment]
I can't really think of a reason not to do this. I'll try to go to 1.0.0 for the next release.

**Comment by nj** [comment]
Time flies when having fun :grin:

**Comment by jnunemaker** [comment]
I'll try to go to 1.0 soon. Closing this though since it is a minor change.

**Comment by henrik** [comment]
@jnunemaker 🎉 Godspeed!

**Pull request closed without merging**
