### PR TITLE
Add multipart support

### PR DESCRIPTION
**Pull request by TheSmartnik**
Hi,
This pull request fixes long-standing issue, of not handling file upload properly #52. No extra dependencies introduced. Tested file upload on rails server, works alright.

### CODE REVIEW

**Comment by jnunemaker** [comment]
Neat. I really don't know much about multipart uploads, but this seems simple and contained so I'm going to merge it. @TheSmartnik are you ok with me pinging you in the future if questions or other pull requests come up about this?

**Comment by TheSmartnik** [comment]
@jnunemaker sure, I'd be super happy to help

**Comment by jirutka** [comment]
This implementation is broken – header `Content-Type` is not added when you pass _any_ header into the request method.

**Comment by TheSmartnik** [comment]
@jirutka oh, I see. Thanks a lot for feedback and pr

**Comment by wayne530** [comment]
May be worth emphasizing for many folks that decided to use `httmultiparty` when on `httparty` < 0.16 that using >= 0.16 + `httmultiparty` causes issues and multi-part form data isn't properly encoded.

**Pull request merged**
