### PR TITLE
This fixes the nil error and enables to read the reponse again.

### LINKED ISSUE #447: HTTP Basic Auth when expecting Net Digest Auth leads to Nil
The Shopware shopsystem uses net digest auth to authentificate remote api calls. So i implemented that. Now the customer has added http basic auth upon that to lock the shop while development.

This lead to this error:
```ruby
blablablacustomerrormessage: undefined method `gsub' for nil:NilClass
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:71:in `parse'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:30:in `initialize'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:7:in `digest_auth'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:187:in `setup_digest_auth'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:178:in `setup_raw_request'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:114:in `perform'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
```

I fixed it in my fork and will send you a pull request. The fix is simple but I would like to have this in the official release.

### PR DESCRIPTION
**Pull request by commel**
fixes #447

### CODE REVIEW

**Comment by jnunemaker** [comment]
Could you add a test that shows what you are fixing so we can avoid breaking it in the future?

**Comment by commel** [comment]
Sure, i can try to do that.

**Comment by commel** [comment]
Hm, i setup everything and dived into net_digest_auth_spec.rb, but i cannot install mongrel for jruby. Do you run the tests on jruby?

**Comment by jnunemaker** [comment]
I do not. The supported matrix is in the travis.yml file, which I guess needs to be updated to support newer versions of ruby as well.

**Comment by commel** [comment]
ok it seems i just need to clearify that i want mongrel for jruby. Will check that out.

**Comment by commel** [comment]
I added the test and ran cucumber.

**Comment by commel** [comment]
hello pls?

**Comment by jnunemaker** [comment]
Open source authors have lives outside of open source. I've been offline due to a death in the family. I actually had this open, pulled locally and was kicking the tires when you commented.

**Comment by commel** [comment]
Sorry to hear that, take your time.

**Comment by jnunemaker** [comment]
Only change I made was this: https://github.com/jnunemaker/httparty/commit/61ade85eae6b62edf7c415d5d961c9b45c40d511

I don't see any point in rescuing just to fail. If an exception is raised, the spec fails which is enough to prevent regression.

Thanks for the fix!

**Comment by commel** [comment]
Great, thanks for the library!

**Pull request merged**
