### PR TITLE
fixed hash syntax

### PR DESCRIPTION
**Pull request by askl56**
Updated hash syntax to Ruby 1.9

### CODE REVIEW

**Comment by jnunemaker** [comment]
It seems like a lot of them are not updated. Why update only some?

**Comment by askl56** [comment]
@jnunemaker Which are not updated?

**Comment by jnunemaker** [comment]
A bunch of them. It seems like it only did the first line in a lot of them, ie: https://github.com/askl56/httparty/blob/master/spec/httparty/connection_adapter_spec.rb#L260-L264

**Comment by askl56** [comment]
I'm working on the script to get it to work better, but I've fixed a few other styling things.

**Comment by jnunemaker** [comment]
Closing as stale.

**Pull request closed without merging**
