### PR TITLE
Reset default request headers

### PR DESCRIPTION
**Pull request by tomatoturnip**
Made a fix to reset default request headers re: #506

### CODE REVIEW

**Comment by CJStadler** [comment]
@tloggins and I ran into this issue and I've verified that this PR fixes it for us. Thanks @tomatoturnip!

**Comment by CJStadler** [comment]
@jnunemaker any chance you could review this? It would be much appreciated 🙇

**Comment by jnunemaker** [comment]
Extremely sorry I overlooked this. Not sure what went wrong.

So the goal of this is to not pass headers to net/http if none are specified in httparty so that net/http's default headers are used?

**Comment by CJStadler** [comment]
@jnunemaker that is correct.

Instead of doing this cleanup before every request perhaps it would be cleaner to either

1. Change `process_headers` to use `default_options[:headers]` instead of `headers`. 
2. Change `headers` to not modify `default_options[:headers]` when it does not receive an arg.

**Comment by CJStadler** [comment]
@jnunemaker sorry to ping you on this again, but it caused another unexpected build failure today. I'm happy to open a PR with either of the above two solutions, if you'd prefer that to the current solution.

**Comment by jnunemaker** [comment]
@CJStadler no prob! I would be fine with 1 or 2. Which feels better to you?

**Comment by jnunemaker** [comment]
@tomatoturnip I'm going to close this one. Again, very sorry I overlooked it. Once I did look it over, I didn't quite understand the problem. Now that I do, I feel that @CJStadler suggestions would be better. My main problem with this one is that it deletes things, which feels a little brute force. I'd rather see some logic that avoids the delete. I'd be happy to merge this if you want to update it or I can wait for @CJStadler's PR.

**Comment by tomatoturnip** [comment]
@jnunemaker No worries. @CJStadler can create the PR. His suggestions sound good. Thanks guys! :)

**Pull request closed without merging**
